version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data: ~/data/mongo
  mysql:
    container_name: mysql
    image: mariadb:10.5.8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - mysql_data:/var/lib/mysql
  apache: 
    container_name: php-apache
    # image: php:7.2.34-apache
    build: .
    ports:
      - 88:80
    volumes:
      - ~/Developer/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ~/WebstormProjects/docker:/var/www/html
      

volumes:
  mysql_data:
    driver: local